import type { ReviewComment, ReviewResult } from "./types.js";
import type { InlineReviewComment } from "./github.js";
import { MODEL_IDS } from "./agents/runner.js";

const SEVERITY_EMOJI: Record<ReviewComment["severity"], string> = {
  critical: "🔴",
  major: "🟠",
  minor: "🟡",
  nit: "⚪",
};

const VERDICT_EMOJI: Record<ReviewResult["verdict"], string> = {
  APPROVE: "✅",
  REQUEST_CHANGES: "🔄",
  NEEDS_DISCUSSION: "💬",
};

/** Builds the body text for a single inline review comment. */
function formatInlineBody(comment: ReviewComment): string {
  const emoji = SEVERITY_EMOJI[comment.severity];
  const lang = comment.category === "types" || comment.category === "async" ? "ts" : "";
  return [
    `${emoji} **${comment.severity}** · ${comment.category}`,
    "",
    comment.issue,
    "",
    "```" + lang,
    comment.suggestion,
    "```",
  ].join("\n");
}

/**
 * Converts blocking + non-blocking findings into inline review comments.
 * Filename and line are taken straight from the agent output; the caller is
 * responsible for filtering against the diff (see github.ts).
 */
export function buildInlineComments(result: ReviewResult): InlineReviewComment[] {
  const out: InlineReviewComment[] = [];
  for (const c of result.blocking) {
    out.push({ path: c.file, line: c.line, body: formatInlineBody(c) });
  }
  for (const c of result.non_blocking) {
    out.push({ path: c.file, line: c.line, body: formatInlineBody(c) });
  }
  return out;
}

/**
 * Top-level review body — short, since per-issue detail lives on inline comments.
 * Used as `body` on the GitHub review object alongside `comments[]`.
 */
export function formatTopLevelSummary(
  result: ReviewResult,
  opts?: { droppedInline?: number }
): string {
  const lines: string[] = [];
  lines.push("## PR Review\n");
  lines.push(`**Verdict:** ${VERDICT_EMOJI[result.verdict]} ${result.verdict}  `);
  lines.push(`**Score:** ${result.score}/10\n`);
  lines.push("### Summary");
  lines.push(`${result.summary}\n`);

  if (result.blocking.length > 0 || result.non_blocking.length > 0) {
    lines.push(
      `### Findings: ${result.blocking.length} blocking · ${result.non_blocking.length} non-blocking\n`
    );
    lines.push("See inline comments on the changed files for specifics.\n");
  }

  if (opts?.droppedInline && opts.droppedInline > 0) {
    lines.push(
      `> ${opts.droppedInline} finding${opts.droppedInline === 1 ? "" : "s"} could not be attached inline (line not in diff). Listed below.\n`
    );
    const overflow = [...result.blocking, ...result.non_blocking];
    overflow.forEach((c, i) => {
      lines.push(`#### ${i + 1}. \`${c.file}\` · line ${c.line} · ${SEVERITY_EMOJI[c.severity]} ${c.severity} · ${c.category}`);
      lines.push(`**Issue:** ${c.issue}`);
      lines.push(`**Fix:** ${c.suggestion}\n`);
    });
  }

  if (result.praise.length > 0) {
    lines.push("### What's good");
    result.praise.forEach((p) => lines.push(`- ${p}`));
    lines.push("");
  }

  if (result.questions.length > 0) {
    lines.push("### Questions");
    result.questions.forEach((q) => lines.push(`- ${q}`));
    lines.push("");
  }

  lines.push("---");
  lines.push("<sub>Generated by pr-review-bot</sub>");
  return lines.join("\n");
}

/**
 * Formats a single review comment into a markdown section.
 *
 * @param comment - The review comment to format
 * @param index - 1-based index for numbering
 * @returns Markdown string for this comment
 */
function formatCommentItem(comment: ReviewComment, index: number): string {
  const emoji = SEVERITY_EMOJI[comment.severity];
  let md = `#### ${index}. \`${comment.file}\` · line ${comment.line} · ${emoji} ${comment.severity} · ${comment.category}\n`;
  md += `**Issue:** ${comment.issue}\n`;
  const lang = comment.category === "types" || comment.category === "async" ? "ts" : "";
  md += `**Fix:**\n\`\`\`${lang}\n${comment.suggestion}\n\`\`\`\n`;
  return md;
}

/**
 * Converts a ReviewResult into a formatted markdown comment suitable for posting on GitHub.
 *
 * @param result - The parsed review result from Claude
 * @returns Formatted markdown string
 */
export function formatComment(result: ReviewResult): string {
  const lines: string[] = [];

  lines.push("## PR Review\n");
  lines.push(`**Verdict:** ${VERDICT_EMOJI[result.verdict]} ${result.verdict}  `);
  lines.push(`**Score:** ${result.score}/10\n`);
  lines.push("### Summary");
  lines.push(`${result.summary}\n`);
  lines.push("---\n");

  // Blocking issues
  if (result.blocking.length > 0) {
    lines.push(`### Blocking Issues (${result.blocking.length})\n`);
    result.blocking.forEach((comment, i) => {
      lines.push(formatCommentItem(comment, i + 1));
    });
    lines.push("---\n");
  }

  // Non-blocking issues
  if (result.non_blocking.length > 0) {
    lines.push(`### Non-blocking (${result.non_blocking.length})\n`);
    result.non_blocking.forEach((comment, i) => {
      lines.push(formatCommentItem(comment, i + 1));
    });
    lines.push("---\n");
  }

  // Praise
  if (result.praise.length > 0) {
    lines.push("### What's good");
    result.praise.forEach((p) => lines.push(`- ${p}`));
    lines.push("");
  }

  // Questions
  if (result.questions.length > 0) {
    lines.push("### Questions");
    result.questions.forEach((q) => lines.push(`- ${q}`));
    lines.push("");
  }

  lines.push("---");
  lines.push(`<sub>Generated by pr-review-bot · model: ${MODEL_IDS.sonnet}</sub>`);

  return lines.join("\n");
}
