import type { ReviewComment, ReviewResult } from "./types.js";

const SEVERITY_EMOJI: Record<ReviewComment["severity"], string> = {
  critical: "🔴",
  major: "🟠",
  minor: "🟡",
  nit: "⚪",
};

const VERDICT_EMOJI: Record<ReviewResult["verdict"], string> = {
  APPROVE: "✅",
  REQUEST_CHANGES: "🔄",
  NEEDS_DISCUSSION: "💬",
};

/**
 * Formats a single review comment into a markdown section.
 *
 * @param comment - The review comment to format
 * @param index - 1-based index for numbering
 * @returns Markdown string for this comment
 */
function formatCommentItem(comment: ReviewComment, index: number): string {
  const emoji = SEVERITY_EMOJI[comment.severity];
  let md = `#### ${index}. \`${comment.file}\` · line ${comment.line} · ${emoji} ${comment.severity} · ${comment.category}\n`;
  md += `**Issue:** ${comment.issue}\n`;
  const lang = comment.category === "types" || comment.category === "async" ? "ts" : "";
  md += `**Fix:**\n\`\`\`${lang}\n${comment.suggestion}\n\`\`\`\n`;
  return md;
}

/**
 * Converts a ReviewResult into a formatted markdown comment suitable for posting on GitHub.
 *
 * @param result - The parsed review result from Claude
 * @returns Formatted markdown string
 */
export function formatComment(result: ReviewResult): string {
  const lines: string[] = [];

  lines.push("## PR Review\n");
  lines.push(`**Verdict:** ${VERDICT_EMOJI[result.verdict]} ${result.verdict}  `);
  lines.push(`**Score:** ${result.score}/10\n`);
  lines.push("### Summary");
  lines.push(`${result.summary}\n`);
  lines.push("---\n");

  // Blocking issues
  if (result.blocking.length > 0) {
    lines.push(`### Blocking Issues (${result.blocking.length})\n`);
    result.blocking.forEach((comment, i) => {
      lines.push(formatCommentItem(comment, i + 1));
    });
    lines.push("---\n");
  }

  // Non-blocking issues
  if (result.non_blocking.length > 0) {
    lines.push(`### Non-blocking (${result.non_blocking.length})\n`);
    result.non_blocking.forEach((comment, i) => {
      lines.push(formatCommentItem(comment, i + 1));
    });
    lines.push("---\n");
  }

  // Praise
  if (result.praise.length > 0) {
    lines.push("### What's good");
    result.praise.forEach((p) => lines.push(`- ${p}`));
    lines.push("");
  }

  // Questions
  if (result.questions.length > 0) {
    lines.push("### Questions");
    result.questions.forEach((q) => lines.push(`- ${q}`));
    lines.push("");
  }

  lines.push("---");
  lines.push("<sub>Generated by pr-review-bot · model: claude-sonnet-4-20250514</sub>");

  return lines.join("\n");
}
