import { Octokit } from "@octokit/rest";
import { fetchPRData, postReviewComment, submitReview } from "./github.js";
import { reviewPR } from "./review.js";
import { formatComment } from "./formatter.js";
import { ReviewParseError } from "./types.js";

/**
 * Returns a formatted timestamp string for log messages.
 *
 * @returns Timestamp in [HH:MM:SS] format
 */
function timestamp(): string {
  return `[${new Date().toTimeString().slice(0, 8)}]`;
}

/**
 * Logs a message with a timestamp prefix.
 *
 * @param message - The message to log
 */
function log(message: string): void {
  console.log(`${timestamp()} ${message}`);
}

/**
 * Parses CLI arguments in --key=value format and falls back to environment variables.
 *
 * @returns Parsed configuration: owner, repo, prNumber, githubToken, anthropicApiKey
 */
function parseArgs(): {
  owner: string;
  repo: string;
  prNumber: number;
  githubToken: string;
} {
  const args = new Map<string, string>();
  for (const arg of process.argv.slice(2)) {
    const match = arg.match(/^--(\w+)=(.+)$/);
    if (match) {
      args.set(match[1], match[2]);
    }
  }

  const owner = args.get("owner") ?? process.env["GITHUB_OWNER"];
  const repo = args.get("repo") ?? process.env["GITHUB_REPO"];
  const prRaw = args.get("pr") ?? process.env["PR_NUMBER"];
  const githubToken = process.env["GITHUB_TOKEN"];

  if (!owner || !repo || !prRaw) {
    console.error(
      "Usage: tsx src/index.ts --owner=<owner> --repo=<repo> --pr=<number>\n" +
        "Or set GITHUB_OWNER, GITHUB_REPO, PR_NUMBER environment variables."
    );
    process.exit(1);
  }

  const prNumber = parseInt(prRaw, 10);
  if (isNaN(prNumber) || prNumber <= 0) {
    console.error(`Invalid PR number: ${prRaw}`);
    process.exit(1);
  }

  if (!githubToken) {
    console.error("GITHUB_TOKEN environment variable is required.");
    process.exit(1);
  }

  if (!process.env["ANTHROPIC_API_KEY"]) {
    console.error("ANTHROPIC_API_KEY environment variable is required.");
    process.exit(1);
  }

  return { owner, repo, prNumber, githubToken };
}

/**
 * Main entrypoint: fetches PR data, runs Claude review, formats and posts results.
 */
async function main(): Promise<void> {
  const { owner, repo, prNumber, githubToken } = parseArgs();

  const octokit = new Octokit({ auth: githubToken });

  log(`Fetching PR #${prNumber} from ${owner}/${repo}...`);
  const prData = await fetchPRData(octokit, owner, repo, prNumber);
  log(`Fetched PR: "${prData.title}" (${prData.files.length} files changed)`);

  log("Sending to Claude for review...");
  let result;
  try {
    result = await reviewPR(prData);
  } catch (error) {
    if (error instanceof ReviewParseError) {
      log("⚠️  Claude returned unparseable response. Posting fallback comment.");
      console.error("Raw response:", error.rawText);

      const fallbackBody =
        "## 🤖 PR Review\n\n" +
        "⚠️ **Review failed:** Claude returned a response that could not be parsed.\n\n" +
        `Error: ${error.message}\n\n` +
        "Please re-run the review or check the logs for details.\n\n" +
        "---\n" +
        "<sub>Generated by pr-review-bot</sub>";

      await postReviewComment(octokit, owner, repo, prNumber, fallbackBody);
      process.exit(1);
    }
    throw error;
  }

  log(`Review complete: ${result.verdict} (${result.score}/10)`);

  const comment = formatComment(result);

  log("Posting review comment...");
  await postReviewComment(octokit, owner, repo, prNumber, comment);

  log("Submitting formal review...");
  await submitReview(octokit, owner, repo, prNumber, result.verdict, comment);

  log("Done!");
  console.log(`\nVerdict: ${result.verdict}`);
  console.log(`Score: ${result.score}/10`);
  console.log(`Blocking issues: ${result.blocking.length}`);
  console.log(`Non-blocking issues: ${result.non_blocking.length}`);
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`${timestamp()} Fatal error: ${message}`);
  process.exit(1);
});
