import { Octokit } from "@octokit/rest";
import { fetchPRData, postReviewComment, submitReview, buildCommentableMap } from "./github.js";
import { orchestrate } from "./orchestrator.js";
import type { AgentTelemetry } from "./agents/types.js";
import { formatComment, formatTopLevelSummary, buildInlineComments } from "./formatter.js";
import { ReviewParseError } from "./types.js";
import type { PRData, ReviewResult } from "./types.js";
import { c, log, logError, hr, createSpinner, readKey } from "./ui/terminal.js";
import { printSummary, addToHistory } from "./ui/display.js";

/** Review pipeline configuration */
export interface ReviewConfig {
  owner: string;
  repo: string;
  prNumber: number;
  githubToken: string;
  dryRun: boolean;
}

/** Result returned from runReview for post-review actions */
export interface ReviewOutcome {
  result: ReviewResult;
  prData: PRData;
  comment: string;
  durationSec: number;
}

/** Runs the full review pipeline: fetch → review → format → post */
export async function runReview(config: ReviewConfig, previousReview?: ReviewResult): Promise<ReviewOutcome | null> {
  const { owner, repo, prNumber, githubToken, dryRun } = config;
  const octokit = new Octokit({ auth: githubToken });

  if (dryRun && !previousReview) {
    log(`${c.yellow}Dry run mode${c.reset} — will not post to GitHub`);
  }

  // Fetch PR (skip if re-review, data already fetched)
  let prData: PRData;
  if (previousReview) {
    const fetchSpinner = createSpinner(`Fetching PR ${c.yellow}#${prNumber}${c.reset}...`);
    prData = await fetchPRData(octokit, owner, repo, prNumber);
    fetchSpinner.stop(`Fetched ${c.dim}(${prData.files.length} files)${c.reset}`);
  } else {
    const fetchSpinner = createSpinner(`Fetching PR ${c.yellow}#${prNumber}${c.reset} from ${c.bold}${owner}/${repo}${c.reset}...`);
    prData = await fetchPRData(octokit, owner, repo, prNumber);
    fetchSpinner.stop(`Fetched: ${c.bold}"${prData.title}"${c.reset} ${c.dim}(${prData.files.length} files)${c.reset}`);
  }

  // Review with spinner + timer
  const reviewStart = Date.now();
  const label = previousReview ? "Re-reviewing" : "Reviewing";
  const reviewSpinner = createSpinner(`${label} with ${c.magenta}Claude${c.reset} multi-agent pipeline...`);

  let result: ReviewResult;
  let gated = false;
  let rejectedCount = 0;
  let rejectedQuestionCount = 0;
  let specialists: string[] = [];
  let telemetry: AgentTelemetry[] = [];
  try {
    const out = await orchestrate({ prData, previous: previousReview, octokit, owner, repo });
    result = out.result;
    gated = out.gated;
    rejectedCount = out.rejected.length;
    rejectedQuestionCount = out.rejectedQuestions.length;
    specialists = out.specialists;
    telemetry = out.telemetry;
  } catch (error) {
    const elapsed = ((Date.now() - reviewStart) / 1000).toFixed(1);
    reviewSpinner.stop(`${c.red}Failed${c.reset} after ${elapsed}s`);
    if (error instanceof ReviewParseError) {
      logError("Claude returned unparseable response.");
      console.error(`${c.dim}Raw:${c.reset}`, error.rawText);
      if (!dryRun) {
        const fallback =
          "## 🤖 PR Review\n\n" +
          "⚠️ **Review failed:** Could not parse Claude's response.\n\n" +
          `Error: ${error.message}\n\n---\n<sub>Generated by pr-review-bot</sub>`;
        await postReviewComment(octokit, owner, repo, prNumber, fallback);
      }
      process.exit(1);
    }
    throw error;
  }

  const durationSec = (Date.now() - reviewStart) / 1000;
  const droppedParts: string[] = [];
  if (rejectedCount > 0) droppedParts.push(`${rejectedCount} finding${rejectedCount === 1 ? "" : "s"}`);
  if (rejectedQuestionCount > 0) droppedParts.push(`${rejectedQuestionCount} question${rejectedQuestionCount === 1 ? "" : "s"}`);
  const tail = gated
    ? `${c.green}gated${c.reset}`
    : droppedParts.length > 0
    ? `${c.dim}(${droppedParts.join(", ")} dropped by validator)${c.reset}`
    : "";
  reviewSpinner.stop(`${label} complete in ${c.yellow}${durationSec.toFixed(1)}s${c.reset} ${tail}`);

  // Print per-agent telemetry — useful in CI logs to see which agents fired and what they cost.
  if (telemetry.length > 0) {
    const specList = specialists.length > 0 ? `[${specialists.join(", ")}]` : "[none]";
    console.log(`${c.dim}Specialists:${c.reset} ${specList}`);
    for (const t of telemetry) {
      const tokens = t.inputTokens !== undefined && t.outputTokens !== undefined
        ? ` ${c.dim}${t.inputTokens}↗${t.outputTokens}↘${c.reset}`
        : "";
      console.log(`  ${c.dim}-${c.reset} ${t.name.padEnd(12)} ${c.dim}${t.model}${c.reset}  ${(t.durationMs / 1000).toFixed(2)}s${tokens}`);
    }
  }

  // Terminal: full breakdown for the human watching.
  const fullComment = formatComment(result);
  console.log(`\n${hr(60)}`);
  console.log(fullComment);
  console.log(`${hr(60)}\n`);

  // GitHub: short summary as review body, per-finding inline comments.
  const inline = buildInlineComments(result);
  const commentable = buildCommentableMap(prData.files);
  const wouldDrop = inline.filter((ic) => !commentable.get(ic.path)?.has(ic.line)).length;
  const summaryBody = formatTopLevelSummary(result, { droppedInline: wouldDrop });

  if (dryRun) {
    log(`${c.yellow}Dry run${c.reset} — not posted yet.`);
  } else {
    const postSpinner = createSpinner("Posting to GitHub...");
    try {
      const { posted, dropped } = await submitReview(
        octokit, owner, repo, prNumber, result.verdict, summaryBody, inline, commentable
      );
      postSpinner.stop(
        `${c.green}Posted${c.reset} ${c.dim}(${posted} inline${dropped.length ? `, ${dropped.length} fell back to summary` : ""})${c.reset}`
      );
    } catch (error) {
      const status = error instanceof Error && "status" in error
        ? (error as { status: number }).status
        : undefined;
      const reason = error instanceof Error ? error.message : String(error);
      postSpinner.stop(`${c.red}Review post rejected${c.reset} ${c.dim}(${status ?? "unknown"})${c.reset}`);
      // Last-ditch fallback: try a plain issue comment so the review isn't lost.
      try {
        await postReviewComment(octokit, owner, repo, prNumber, summaryBody);
        log(`${c.yellow}Posted as plain issue comment instead${c.reset} ${c.dim}(${reason})${c.reset}`);
      } catch (commentError) {
        const commentReason = commentError instanceof Error ? commentError.message : String(commentError);
        logError(`Could not post review or comment: ${commentReason}`);
        // Don't fail the workflow — the review was produced and printed; this is operator-fixable.
      }
    }
  }

  // Track in session history
  addToHistory({
    repo: `${owner}/${repo}`,
    pr: prNumber,
    title: prData.title,
    verdict: result.verdict,
    score: result.score,
    time: new Date().toTimeString().slice(0, 8),
    duration: durationSec,
  });

  printSummary(result.verdict, result.score, result.blocking.length, result.non_blocking.length, result.praise.length, durationSec);

  // Post-review actions (interactive only — no-op in CI / non-TTY)
  await postReviewActions(config, result, prData, summaryBody, inline, commentable);

  return { result, prData, comment: summaryBody, durationSec };
}

/** Shows post-review action menu. Skipped automatically in CI / non-TTY environments. */
async function postReviewActions(
  config: ReviewConfig,
  result: ReviewResult,
  _prData: PRData,
  summaryBody: string,
  inline: ReturnType<typeof buildInlineComments>,
  commentable: Map<string, Set<number>>
): Promise<void> {
  if (!process.stdin.isTTY) return;

  const { owner, repo, prNumber, githubToken, dryRun } = config;
  const octokit = new Octokit({ auth: githubToken });

  const canPost = dryRun;
  const canReReview = result.verdict !== "APPROVE";

  if (!canPost && !canReReview) return;

  const options: string[] = [];
  if (canPost) options.push(`${c.yellow}p${c.reset}  Post this review to GitHub`);
  if (canReReview) options.push(`${c.yellow}r${c.reset}  Re-review with previous context`);
  options.push(`${c.dim}any other key to continue${c.reset}`);

  console.log(`  ${options.join("\n  ")}`);

  const key = await readKey();

  if (key === "p" && canPost) {
    const postSpinner = createSpinner("Posting to GitHub...");
    await submitReview(octokit, owner, repo, prNumber, result.verdict, summaryBody, inline, commentable);
    postSpinner.stop(`${c.green}Posted to GitHub!${c.reset}`);
  } else if (key === "r" && canReReview) {
    console.log("");
    log(`Re-reviewing with previous context...`);
    await runReview(config, result);
  }
}
