import { Octokit } from "@octokit/rest";
import { fetchPRData, postReviewComment, submitReview } from "./github.js";
import { reviewPR } from "./review.js";
import type { ReviewMode } from "./review.js";
import { formatComment } from "./formatter.js";
import { ReviewParseError } from "./types.js";
import { c, log, logError, hr } from "./ui/terminal.js";
import { printSummary } from "./ui/display.js";

/** Review pipeline configuration */
export interface ReviewConfig {
  owner: string;
  repo: string;
  prNumber: number;
  githubToken: string;
  dryRun: boolean;
  mode: ReviewMode;
}

/** Runs the full review pipeline: fetch → review → format → post */
export async function runReview(config: ReviewConfig): Promise<void> {
  const { owner, repo, prNumber, githubToken, dryRun, mode } = config;
  const octokit = new Octokit({ auth: githubToken });

  if (dryRun) {
    log(`${c.yellow}Dry run mode${c.reset} — will not post to GitHub`);
  }

  log(`Fetching PR ${c.cyan}#${prNumber}${c.reset} from ${c.bold}${owner}/${repo}${c.reset}...`);
  const prData = await fetchPRData(octokit, owner, repo, prNumber);
  log(`Fetched: ${c.bold}"${prData.title}"${c.reset} ${c.dim}(${prData.files.length} files)${c.reset}`);

  log(`Sending to ${c.magenta}Claude${c.reset} for review ${c.dim}(${mode})${c.reset}...`);
  let result;
  try {
    result = await reviewPR(prData, mode);
  } catch (error) {
    if (error instanceof ReviewParseError) {
      logError("Claude returned unparseable response.");
      console.error(`${c.dim}Raw:${c.reset}`, error.rawText);
      if (!dryRun) {
        const fallback =
          "## 🤖 PR Review\n\n" +
          "⚠️ **Review failed:** Could not parse Claude's response.\n\n" +
          `Error: ${error.message}\n\n---\n<sub>Generated by pr-review-bot</sub>`;
        await postReviewComment(octokit, owner, repo, prNumber, fallback);
      }
      process.exit(1);
    }
    throw error;
  }

  log(`Review complete!`);
  const comment = formatComment(result);

  if (dryRun) {
    console.log(`\n${hr(60)}`);
    console.log(comment);
    console.log(`${hr(60)}\n`);
    log(`${c.yellow}Dry run${c.reset} — skipped posting.`);
  } else {
    log("Posting review comment...");
    await postReviewComment(octokit, owner, repo, prNumber, comment);
    log("Submitting formal review...");
    await submitReview(octokit, owner, repo, prNumber, result.verdict, comment);
    log(`${c.green}Posted to GitHub!${c.reset}`);
  }

  printSummary(result.verdict, result.score, result.blocking.length, result.non_blocking.length, result.praise.length);
}
